version: '{build}'
skip_tags: true
shallow_clone: true
clone_depth: 1
build: off
environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest || (timeout 30 && npm -g install npm@latest)
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install || (timeout 30 && npm install)
test_script:
  - node --version
  - npm --version
  - npm test || (timeout 30 && npm test)
